language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # Travis CI는 S3로 디렉토리만 업로드 가능
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy dir 생성
  - mv before-deploy/before-deploy.zip deploy/junsu-springboot2-webservice-demo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings value
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings value
    bucket: junsu-springboot-build # S3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리, 지정된 디렉토리 내 파일들만 S3로 전송
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: junsu-springboot-build
    key: junsu-springboot2-webservice-demo.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    applicaiton: junsu-springboot2-webservice # 웹콘솔에서 등록한 CodeDeploy application
    deployment_group: junsu-springboot2-webservice-group # 웹콘솔에서 등록한 CodeDeploy group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - melon8372@gmail.com
